import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { Box, CssBaseline } from '@mui/material';
import SideBar from "@/components/SideBar/SideBar";
import ReduxProvider from "@/utils/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <ReduxProvider>
            <Box sx={{ display: 'flex' }}>
              <Box sx={{ position: 'sticky', top: 0, width: { xs: 0, lg: '300px' }, height: '100vh' }}>
                <SideBar/>
              </Box>
              <Box sx={{ width: { xs: '100%', lg: 'calc(100vw - 300px)' }, minHeight: '100vh', bgcolor: '#f4f8fe'}}>
                {children}
              </Box>
            </Box>
          </ReduxProvider>
        </AppRouterCacheProvider>
        <CssBaseline/>
      </body>
    </html>
  );
};
